# Generated by Django 3.1.3 on 2021-01-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20210114_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='measurement',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
